version: "2.2"
services:

  ### Zookeeper ###

  zoo1:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zoo1
    ports:
    - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888

  ### Kafka ###

  kafka-cp-kafka-headless:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka-cp-kafka-headless
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-cp-kafka-headless:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
    - zoo1

  ### Flink Job Cluster ###

  flink-master:
    image: ${FLINK_DOCKER_IMAGE_NAME:-demo-flink-job:latest}
    ports:
      - "8081:8081"
    command: job-cluster --job-classname com.ververica.field.dynamicrules.Main -Djobmanager.rpc.address=flink-master -Dparallelism.default=1 --data-source kafka --rules-source kafka --sqls-source kafka --alerts-sink kafka --rules-export-sink kafka --latency-sink kafka --kafka-host kafka-cp-kafka-headless --kafka-port 9092
    depends_on:
    - kafka-cp-kafka-headless

  flink-task-manager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-demo-flink-job:latest}
    command: task-manager -DXmx6g -DXms6g  -Djobmanager.rpc.address=flink-master -Dtaskmanager.memory.network.max=128m -Dtaskmanager.memory.framework.off-heap.size=512m -Dtaskmanager.memory.process.size=3g
    scale: ${DEFAULT_PARALLELISM:-1}
    depends_on:
    - kafka-cp-kafka-headless

  ### Spring Boot Demo###

  demo:
    image: demo-webapp:latest
    hostname: demo
    ports:
      - "5656:5656"
    depends_on:
      - zoo1
      - kafka-cp-kafka-headless
